= Arkadion - Halbschwergewicht R1 (episch)

WARNING: Noch in Arbeit!

== Quellen und Ressourcen
* https://www.youtube.com/watch?v=9UB5x8JzAiQ&ab_channel=HectorHectorson-HectorLectures[Video Hector]

== Chat-Makros

== Marks

== Vierfachklaue (Quadruple Crossing)
Rollen-Proteans

== Milchtritt (Biscuit Maker)
Tankbuster

== Sieben Leben (Nine Lives)
Äther freisetzen für Klone

== Doppelklaue (One-Two Paw)
Halb-Raum

== Seelenschatten (Soulshade)
Klone aus freigesetztem Äther erschaffen

//Sieben Leben

== Vierfache/Doppelte Kralle (Double/Quadruple Swipe)
vierfach -> Pairs +
doppelt -> Stacks

// Seelenschatten

== Vierfachklauensprung (Leaping Quadruple Crossing)
Vierfachklaue mit Verschieben

== Blutiger Rundumkratzer (Bloody Scratch)
Raidwide

== Mäusejagd (Mouser)
Plattform wird zerstört +
hinten links am Boss anfangen +
hinten rechts am Boss betrachten +
einmal oder zweimal ausweichen

== Feline Nachahmung (Copycat)
Add schlägt mit Präziser Höhenflug +
2 Mal direkter Hit, 2 Mal mit Hochwerfen +
Boss gebückt -> Hochwerfen

//Milchtritt

== Schockwelle (Shockwave)
Knockback zu neu generierten Plattformen

== Zwei Klone
Nine Lives + Doppelklauensprung (Leaping One-Two Paw) + Soulshade +
Nine Lives + Leaping Quadruple Crossing + Soulshade +
Katerstrophaler Wind (Tempestuous Tear) (Line-Stacks) +
Krallenschneider (Nailchipper) (Spread-Marks müssen bei Rollen-Proteans die zweiten Baits übernehmen) +
Nailchipper-Marks am Ende voneinander weg, können nicht-markierte ruhig treffen

// Raidwide

== Mäusejagd (Mouser) 2
Ausweichen genau wie beim ersten Mal

=== Überschattung (Overshadow)
Line-Stack

=== Spreizklaue (Splintering Nails)
Rollen-Stacks + 
Tanks -> Heiler -> DDs

// tb
// shockwave

== Katzenterror (Raining Cats)
Tethers

== Feliner Beutezug (Copycat)
Devour mit Halb-Raum

== Mäusejagd (Mouser) Enrage
alle Plattformen werden zerstört
